"""Create_Category_Location_Museum_Exposition_tables

Revision ID: c50352cd52cd
Revises: 
Create Date: 2025-12-25 20:16:08.618585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c50352cd52cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('category_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('submission', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('teg', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('eipsk', sa.Integer(), nullable=True),
    sa.Column('service_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('showcase', sa.String(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('webpage', sa.String(length=255), nullable=False),
    sa.Column('visitors', postgresql.ENUM('adult', 'child', 'all', name='enum_visitor'), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expositions')
    op.drop_table('museums')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
